name: /Users/jack/Repos/apnea-predictor/.conda
channels:
  - defaults
dependencies:
  - aom=3.12.1=ha237518_0
  - appnope=0.1.4=py314hca03da5_0
  - asttokens=3.0.0=py314hca03da5_0
  - blas=1.0=openblas
  - bottleneck=1.4.2=py314hdbb4bc7_1
  - bzip2=1.0.8=h80987f9_6
  - ca-certificates=2025.12.2=hca03da5_0
  - cairo=1.18.4=h191e429_0
  - comm=0.2.3=py314hca03da5_0
  - contourpy=1.3.3=py314h20e30b6_0
  - cycler=0.12.1=py314hca03da5_0
  - dav1d=1.2.1=h80987f9_0
  - debugpy=1.8.16=py314h50f4ffc_1
  - decorator=5.2.1=py314hca03da5_0
  - executing=2.2.1=py314hca03da5_0
  - expat=2.7.3=h50f4ffc_4
  - fontconfig=2.15.0=h29935d0_0
  - fonttools=4.60.1=py314h254cc4a_0
  - freetype=2.13.3=h47d26ad_0
  - fribidi=1.0.10=h1a28f6b_0
  - gettext=0.21.0=hbdbcc25_2
  - graphite2=1.3.14=hc377ac9_1
  - harfbuzz=10.2.0=he637ebf_1
  - icu=73.1=h313beb8_0
  - ipykernel=6.31.0=py314h7136c26_0
  - ipython=9.7.0=py314hca03da5_0
  - ipython_pygments_lexers=1.1.1=py314hca03da5_0
  - jedi=0.19.2=py314hca03da5_0
  - joblib=1.5.3=py314hca03da5_0
  - jpeg=9f=h2f69dba_0
  - jupyter_client=8.6.3=py314hca03da5_1
  - jupyter_core=5.9.1=py314hca03da5_0
  - kiwisolver=1.4.9=py314haeee614_0
  - lcms2=2.17=h7418793_0
  - lerc=4.0.0=h313beb8_0
  - libavif=1.3.0=h839b4eb_0
  - libcxx=20.1.8=hd7fd590_1
  - libdeflate=1.22=h80987f9_0
  - libexpat=2.7.3=h50f4ffc_4
  - libffi=3.4.4=hca03da5_1
  - libgfortran5=15.2.0=hb654fa1_1
  - libglib=2.84.4=h7a3292d_0
  - libiconv=1.16=h80987f9_3
  - libmpdec=4.0.0=h80987f9_0
  - libopenblas=0.3.30=hf2bb037_2
  - libopenjpeg=2.5.4=haa24f5a_1
  - libpng=1.6.50=h5c318fc_0
  - libsodium=1.0.20=h897f8a9_0
  - libtiff=4.7.1=h367c460_0
  - libwebp-base=1.6.0=h92b2d59_0
  - libxml2=2.13.9=h528a072_0
  - libzlib=1.3.1=h5f15de7_0
  - llvm-openmp=20.1.8=he822017_0
  - lz4-c=1.9.4=h313beb8_1
  - matplotlib=3.10.7=py314hca03da5_0
  - matplotlib-base=3.10.7=py314haeb1505_0
  - matplotlib-inline=0.2.1=py314hca03da5_0
  - narwhals=2.7.0=py314hca03da5_0
  - ncurses=6.5=hee39554_0
  - nest-asyncio=1.5.1=pyhd3eb1b0_0
  - numexpr=2.14.1=py314h4402d01_0
  - numpy=2.3.5=py314hde9b8b7_0
  - numpy-base=2.3.5=py314hb4b2851_0
  - openjpeg=2.5.4=h959fc53_1
  - openssl=3.0.18=h9b4081a_0
  - packaging=25.0=py314hca03da5_1
  - pandas=2.3.3=py314heb7d0cc_1
  - parso=0.8.5=py314hca03da5_0
  - pcre2=10.46=h1dacb4a_0
  - pexpect=4.9.0=py314hca03da5_1
  - pillow=11.3.0=py314hcf7bca3_0
  - pip=25.3=pyh0d26453_0
  - pixman=0.46.4=h09dc60e_0
  - platformdirs=4.5.0=py314hca03da5_0
  - plotly=6.3.0=py314h7136c26_0
  - prompt-toolkit=3.0.52=py314hca03da5_1
  - prompt_toolkit=3.0.52=hd3eb1b0_1
  - psutil=7.0.0=py314haa24f5a_1
  - ptyprocess=0.7.0=pyhd3eb1b0_3
  - pure_eval=0.2.3=py314hca03da5_0
  - pygments=2.19.2=py314hca03da5_0
  - pyparsing=3.2.5=py314hca03da5_0
  - python=3.14.2=h1858270_101_cp314
  - python-dateutil=2.9.0post0=py314hca03da5_2
  - python-tzdata=2025.2=pyhd3eb1b0_0
  - python_abi=3.14=2_cp314
  - pytz=2025.2=py314hca03da5_0
  - pyzmq=27.1.0=py314h5a8c52c_1
  - readline=8.3=h0b18652_0
  - scikit-learn=1.8.0=py314hfa3d80f_0
  - scipy=1.16.3=py314h18857b0_0
  - seaborn=0.13.2=py314hca03da5_3
  - six=1.17.0=py314hca03da5_0
  - sqlite=3.51.1=hab6afd1_0
  - stack_data=0.6.3=py314hca03da5_0
  - threadpoolctl=3.5.0=py314h7136c26_1
  - tk=8.6.15=hcd8a7d5_0
  - tornado=6.5.1=py314h75312c3_0
  - traitlets=5.14.3=py314hca03da5_0
  - tzdata=2025b=h04d1e81_0
  - wcwidth=0.2.14=py314hca03da5_0
  - xz=5.6.4=h80987f9_1
  - zeromq=4.3.5=h2c7f8f0_1
  - zlib=1.3.1=h5f15de7_0
  - zstd=1.5.7=h817c040_0
prefix: /Users/jack/Repos/apnea-predictor/.conda
